### ISSUE TITLE
Missing feature: Timestamp precision

### ISSUE THREAD

**Issue by hpsjakob** [aprimadi/influxdb2#13]
Hi,

I'm just using this Lib for writing a script that populates an InfluxDB and am quite happy with it!
During that project I came across the following issue:
As far as I could see this lib always writes the timestamp with nanoseconds precision.

Do you plan do add support for the other available precision-options?
https://docs.influxdata.com/influxdb/v2.5/reference/syntax/line-protocol/#timestamp

Would you accept a Merge Request for that feature?

Regards,
Jakob

**Comment by aprimadi** [comment]
> Do you plan do add support for the other available precision-options?

Not right now, I'm kinda busy with work.

> Would you accept a Merge Request for that feature?

Sure, pull request are always welcome.

**Comment by hpsjakob** [comment]
Ok, so do you have a preference how the API should look like?

We could do:
`````rust
pub fn timestamp(mut self, value: i64, precision: TimestampPrecision) -> Self {
}
````

or:
`````rust
pub fn timestamp(mut self, value: Timestamp) -> Self {
}
````

with Timestamp an enum. 

https://docs.rs/influxdb/latest/influxdb/ has chosen then second approach.

**Comment by hpsjakob** [comment]
I just saw that for influxdb 2 it's different...
I'll create a MR and come back to you.
