### ISSUE TITLE
Can'd find Datapoint::data_point_to_vec()

### ISSUE THREAD

**Issue by 3BK** [aprimadi/influxdb2#21]
Can someone please point me to the Datapoint::data_point_to_vec() method?  
It's referenced in the code, but I can't seem to locate the logic.

Thanks!

**Comment by 3BK** [comment]
Should I be looking for WriteDataPointExt or DataPointExt?

I'm asking because influx measurements containing timestamps appear to be silently discarded.

Thanks.

**Comment by aprimadi** [comment]
Hello, what version do you use?
