### ISSUE TITLE
Request to add additional root certificates

### ISSUE THREAD

**Issue by 3BK** [aprimadi/influxdb2#22]
.add_root_certificate(cert)

Please advise if you would like me to supply the change.

**Comment by 3BK** [comment]
Not adding additional root certificates breaks the app.
Adding additional root certificates to OS breaks the compiler .

**Comment by aprimadi** [comment]
I'm curious what is the motivation for this?

**Comment by 3BK** [comment]
The motivation is to avoid breaking the [rust compiler](https://www.rust-lang.org/) and your [influxdb2](https://github.com/aprimadi/influxdb2) client.

Elaboration:
 - Those new to influxdb2 may install [influxdb2 OSS](https://docs.influxdata.com/influxdb/v2.6/) locally.
     - At present, by design:
           - rust appears to emit an error and refuses to compile if a self-signed CA has been added to the target.
     - At present, by design, your client:
           - will not connect to the server, unless it trusts the server's CA 
           - will not accept addtional trusted root certificates to establish trust, 
           - meaning: 
                - if the server's CA is self-signed, the CA needs to be installed on the target
                - we have a condundrum
    - it is my recommendation that:
          -  we add the ability to allow the client to accept additional certificates so that your client can increase it's "marketshare"

**Comment by aprimadi** [comment]
Anyone else having the same issue? I've never experienced this issue even when installing influxdb2 locally or using Docker. 

When using Docker sometimes it shows the problem of not having the correct certificate but it can be solved by installing the SSL package.

**Comment by aprimadi** [comment]
Since installing a CA certificate is at the network level can't it be handled at the network level? Like by passing in the connection factory that first download the ca certificate.

Anyway this is suspect since I don't believe it should be handled at the library level since CA certificate should be handled at the network level. Pull request is welcome but no guarantee I'll accept it.

**Comment by 3BK** [comment]
I have attached the proposed change above.

**Comment by aprimadi** [comment]
Yeah looking at the code, I believe this shouldn't be part of the Influxdb2 library because user is able to achieve the same thing by just instantiating a `reqwest::Client` and creating an influxdb2::Client manually.

**Comment by 3BK** [comment]
Can you please elaborate?

**Comment by 3BK** [comment]
It sounds like you are saying fork the code base.
