### ISSUE TITLE
Why is the QueryResult new function src/api/query.rs in influxdb2 explicitly specifying lifetimes ?

### ISSUE THREAD

**Issue by 3BK** [aprimadi/influxdb2#26]
https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

**Comment by aprimadi** [comment]
Seems like just code styling, I allow different code styles as long as it's pretty sensible. Using explicit lifetime vs implicit lifetime achieves the same thing.

Also since this is a question, closing this.
