### ISSUE TITLE
Derive macro FromDataPoint not working for nested types?

### ISSUE THREAD

**Issue by h4l7** [aprimadi/influxdb2#45]
The following usage of the `FromDataPoint` derive macro yields an error:
```
#[derive(Debug, Default, Clone, PartialEq, Eq, FromDataPoint)]
pub struct Record {
    pub metadata: Metadata,
    pub releases: Vec<Content>,
}

#[derive(Debug, Default, Clone, PartialEq, Eq, FromDataPoint)]
pub struct Metadata {
    pub version: String,
}

#[derive(Debug, Default, Clone, PartialEq, Eq, FromDataPoint)]
pub struct Content {
    pub name: String,
    pub values: String,
}
```

gives

```
error: proc-macro derive panicked
 --> src/record.rs:6:48
  |
6 | #[derive(Debug, Default, Clone, PartialEq, Eq, FromDataPoint)]
  |                                                ^^^^^^^^^^^^^
  |
  = help: message: Metadata is not handled
```

Is there a special way to handle nested values such as these? Thank you.

**Comment by Boudewijn26** [comment]
Please do forgive me for chiming in, but as far as I understand all influx 2 queries return tables (one or more). It might help if you specified which query (roughly) you are running that you'd expect to return a nested result

**Comment by h4l7** [comment]
I am new to InfluxDB, so it's entirely possible I'm misunderstanding the problem.
We have telegraf ingesting json_v2 data into the given bucket, so the intention here is to query for the structured JSON conformant to the struct we've defined.
