### ISSUE TITLE
Using influxdb2 crate in a non-async context

### ISSUE THREAD

**Issue by knepe** [aprimadi/influxdb2#46]
Hello,

For starters, I'm pretty new to Rust. 
I want to use this crate for writing data to influxdb in a non-async context. That means I'm in a context where I cannot use async-trait (I'm using riker: https://riker.rs). 
Is this possible? Thanks

**Comment by Boudewijn26** [comment]
Hi,

In genuine non-async contexts, you'd have to try [block_on](https://docs.rs/futures-executor/latest/futures_executor/fn.block_on.html). Though that might deadlock depending on the exact specifics of what you're doing.

But from what I'm seeing riker does have the ability to deal with futures and in fact uses then under the hood: https://riker.rs/futures/.

I hope that answers you question

**Comment by knepe** [comment]
Ah, that looks lite it should work 🙂 Thank you! 👍
