### ISSUE TITLE
Exposing the underlying reqwest client to support custom mTLS certificates.

### ISSUE THREAD

**Issue by h4l7** [aprimadi/influxdb2#47]
Hello! My use case requires me to support mutual authentication between the InfluxDB2 server & the client. Adding the server's CA certificate to the client is simple enough by modifying the CA certificates present on the host machine, but I don't see a way to provide a TLS certificate to this crate in order to not default to a self-signed client certificate.

If I'm understanding correctly, the issue I'm running into occurs because the underlying `reqwest::Client` object is private (https://docs.rs/influxdb2/latest/src/influxdb2/lib.rs.html#159). If this were public, or if some kind of pass-through were provided, I believe I understand how to provide a custom TLS configuration to the client. Is there another way? If my understanding is correct and this is a feature you are willing to support, I would be happy to contribute.

Thank you.

**Comment by aprimadi** [comment]
Hi @h4l7 PR is welcome. Perhaps add a method into existing client builder to support custom reqwest::ClientBuilder.

**Comment by aprimadi** [comment]
Thank you for a clear explanation of the problem.

**Comment by h4l7** [comment]
Thank you. I'll open a PR when ready.

**Comment by h4l7** [comment]
See: https://github.com/aprimadi/influxdb2/pull/48
