### ISSUE TITLE
Question: timestamp

### ISSUE THREAD

**Issue by daniel-finnan** [aprimadi/influxdb2#7]
The `timestamp` field within the `DataPointBuilder` struct is a i64, however, if I want to set the timestamp myself in nanoseconds I'd be using u128. So when using `DataPoint::builder` I get a mismatched types error. Is there something I'm missing? Of course, I note that u128 isn't listed in the supported types. Many thanks, a baby Rustacean.

**Comment by Samiisd** [comment]
hi, can't `i64` support ns precision? when using i64 max value as an NS UTC timestamp, you should be able to have enough for until 2262

![image](https://user-images.githubusercontent.com/25390832/193035682-833cd476-ab3e-4ca6-b774-b7a7d4d9d0c2.png)

also, not sure if that helps, but this lib doesn't precise the precision in it's `write` request API call, therefore default precision is applied: ns (https://docs.influxdata.com/influxdb/v2.4/reference/glossary/#unix-timestamp) 


To resume:
- I think i64 should be enough
- sent to influxdb in nano-seconds by default

I might be missing something as well tho.

**Comment by daniel-finnan** [comment]
I guess, but Rust's own implementation `as_nanos` returns a u128.

So if you're doing something like:

`let time = SystemTime::now().duration_since(UNIX_EPOCH).unwrap();`

And passing that into the `DataPoint::builder` then it'll throw a mismatched types error.

I suppose I could find a way to cast from u128 to i64, since as you point out, this won't be an issue for another 240 years or so!
